version: "2"

services:
  jekyll:
    build: .
    volumes: 
      - "./:/src"
    ports:
      - "4000:4000"
    expose:
      - 4000
    command: "serve --watch --incremental --force_polling -H 0.0.0.0"
